### ISSUE TITLE
为什么index_static下的文件都报404错误呢？

### ISSUE THREAD

**Issue by notfindmeh** [iaboaix/NetworkGraph#7]
[07/May/2021 20:08:13] "GET / HTTP/1.1" 200 30319
[07/May/2021 20:08:13] "GET /static/js/thirdPart/saveSvgAsPng.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/css/font-awesome-4.7.0/css/font-awesome.min.css HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/thirdPart/d3.min.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/css/style.css HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/thirdPart/jquery-3.3.1.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/tools.js HTTP/1.1" 404 77
----------------------------------------[07/May/2021 20:08:13] "GET /static/js/upOrDownload.js HTTP/1.1" 404 77

Exception occurred during processing of request from ('127.0.0.1', 60326)
[07/May/2021 20:08:13] "GET /static/js/index.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/css/smartMenu.css HTTP/1.1" 404 77
Traceback (most recent call last):
[07/May/2021 20:08:13] "GET /static/js/thirdPart/smartMenu.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/showControl.js HTTP/1.1" 404 77
  File "D:\Python\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\Python\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\Python\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\Python\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "D:\Python\lib\site-packages\django\core\servers\basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
[07/May/2021 20:08:13] "GET /static/js/selectFunction.js HTTP/1.1" 404 77
  File "D:\Python\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
[07/May/2021 20:08:13] "GET /static/js/treeGraph.js HTTP/1.1" 404 77
ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。
----------------------------------------
[07/May/2021 20:08:13] "GET /static/js/barGraph.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/tools/route.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/networkGraph.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/transform.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/css/style.css HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/css/font-awesome-4.7.0/css/font-awesome.min.css HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/index.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/image/userhead/anonymous.jpg HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/tools.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/showControl.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/upOrDownload.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/transform.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/barGraph.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/selectFunction.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/treeGraph.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/networkGraph.js HTTP/1.1" 404 77
[07/May/2021 20:08:13] "GET /static/js/tools/route.js HTTP/1.1" 404 77
Performing system checks...

System check identified no issues (0 silenced).
May 07, 2021 - 20:10:32
Django version 2.1.7, using settings 'NetworkGraph.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[07/May/2021 20:10:33] "GET / HTTP/1.1" 200 30427
[07/May/2021 20:10:33] "GET /index_static/js/thirdPart/d3.min.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/thirdPart/saveSvgAsPng.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/css/smartMenu.css HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/thirdPart/smartMenu.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/css/style.css HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/thirdPart/jquery-3.3.1.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/index.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/showControl.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/css/font-awesome-4.7.0/css/font-awesome.min.css HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/transform.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/barGraph.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/upOrDownload.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/tools.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/selectFunction.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/treeGraph.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/networkGraph.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/tools/route.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/thirdPart/smartMenu.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/css/style.css HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/css/smartMenu.css HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/css/font-awesome-4.7.0/css/font-awesome.min.css HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /static/image/userhead/anonymous.jpg HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/index.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/tools.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/showControl.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/upOrDownload.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/transform.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/barGraph.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/selectFunction.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/treeGraph.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/networkGraph.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/js/tools/route.js HTTP/1.1" 404 77
[07/May/2021 20:10:33] "GET /index_static/image/logo.ico HTTP/1.1" 404 77

Process finished with exit code 0

**Comment by zn-yyds** [comment]
我也一样，不左到怎么解决

**Comment by zn-yyds** [comment]
我也一样不知道怎么解决

**Comment by LoveZQY** [comment]
我已收到您的邮件！

**Comment by wxm66** [comment]
请问有解决方案了吗

**Comment by LoveZQY** [comment]
我已收到您的邮件！

**Comment by wxm66** [comment]
> 请问有解决方案了吗

已解决。启动 django 时必须带上 --insecure.
